name: Deploy infrastructure
description: Deploy Azure infrastructure including resource group
author: LayZeeDK

inputs:
  application_name:
    description: The application name used as prefix for Azure resources
    required: true
  location:
    description: The location for Azure resources
    required: true
  repository_token:
    description: 'GitHub Personal Access Token (PAT) with the "repo", "workflow", and "write:packages" permissions'
    required: true
  subscription_id:
    description: The Azure subscription ID
    required: true

outputs:
  deployment_token:
    description: The deployment token for the Azure Static Web App
    value: ${{ steps.deployment_token.outputs.deployment_token }}
  host_name:
    description: 'The host name of the Azure Static Web App, for example "gentle-bush-0db02ce03.azurestaticapps.net"'
    value: ${{ steps.deploy.outputs.staticWebAppHostName }}

runs:
  using: composite
  steps:
    - id: repo
      env:
        SERVER_URL: ${{ github.server_url }}
        REPO: ${{ github.repository }}
      run: echo "::set-output name=http_url::${{ env.SERVER_URL }}/${{ env.REPO }}"
      shell: bash
    - id: deploy
      uses: Azure/arm-deploy@v1
      env:
        APPLICATION_NAME: ${{ inputs.application_name }}
        LOCATION: ${{ inputs.location }}
        REPOSITORY_TOKEN: ${{ inputs.repository_token }}
        REPOSITORY_URL: ${{ steps.repo.outputs.http_url }}
      with:
        scope: subscription
        subscriptionId: ${{ inputs.subscriptionId }}
        region: ${{ env.AZURE_LOCATION }}
        template: build/main.bicep
        parameters: applicationName="${{ env.APPLICATION_NAME }}" location="${{ env.LOCATION }}" repositoryToken="${{ env.REPOSITORY_TOKEN }}" repositoryUrl="${{ env.REPOSITORY_URL }}"
    - id: deployment_token
      uses: ./.github/actions/staticwebapps-get-deployment-token
      with:
        name: ${{ steps.deploy.outputs.staticWebAppName }}
